services:
  - type: web
    name: shoe-store-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
